enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - '@electron-forge/*'
  - electron
  - node-abi

yarnPath: .yarn/releases/yarn-4.10.3.cjs
