compressionLevel: 0

enableScripts: false

enableGlobalCache: true

# 1 week
npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - 'lerna/*'

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.2.cjs
