enableScripts: false

# 1 week
npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - '@electron-forge/*'
  - 'electron'

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.2.cjs
