enableScripts: false

# 1 week
npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - '@bitdisaster/exe-icon-extractor'
  - 'electron-winstaller'
  - 'macos-alias'

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.2.cjs
