catalog:
  vite: ^8.0.0
  vitest: ^5.0.1

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - '@electron-forge/*'
  - '@electron-internal/*'
  - create-electron-app
  - electron
  - node-abi

yarnPath: .yarn/releases/yarn-4.18.0.cjs
