blank_issues_enabled: false

contact_links:
  - name: Documentation Issues
    url: https://github.com/electron-forge/electron-forge-docs/issues/new
    about: Documentation issues / pull requests should be filed in the website repository.
