blank_issues_enabled: false

contact_links:
  - name: Question
    url: https://discord.gg/invite/APGC3k5yaH
    about: 'Please ask questions about using Electron Forge in the official Electron Discord server, at the #electron-forge channel.'
  - name: Documentation Issues
    url: https://github.com/electron-forge/electron-forge-docs/issues/new
    about: Documentation issues / pull requests should be filed in the website repository.
