import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { styleText } from 'node:util';

import {
  getNameFromAuthor,
  move,
  pathExists,
} from '@electron-forge/core-utils';
import { MakerBase, MakerOptions } from '@electron-forge/maker-base';
import { toMsixArch } from '@electron-forge/maker-msix';
import { ForgePlatform } from '@electron-forge/shared-types';
import { packageMSIX } from 'electron-windows-msix';

import { MakerAppXConfig } from './Config.js';

/**
 * `electron-windows-store` options that have no `electron-windows-msix`
 * equivalent. They are ignored with a warning.
 */
const UNSUPPORTED_OPTIONS = [
  'containerVirtualization',
  'createConfigParams',
  'createPriParams',
  'deploy',
  'desktopConverter',
  'expandedBaseImage',
  'finalSay',
  'flatten',
  'makeappxParams',
] as const satisfies readonly (keyof MakerAppXConfig)[];

/**
 * Asset file names the `AppxManifest.xml` generated by `electron-windows-msix`
 * refers to. `makeappx.exe` refuses to pack a layout that is missing any of
 * them, so a custom `assets` folder must provide them (unless a custom
 * `manifest` names its own assets).
 */
const REQUIRED_ASSETS = [
  'icon.png',
  'Square44x44Logo.png',
  'Square150x150Logo.png',
];

// Where electron-windows-store used to look for the Windows SDK tools. When
// `windowsKit` is unset, electron-windows-msix only checks a single hard-coded
// SDK version, so search these folders first to keep existing machines
// building.
const WINDOWS_KIT_ROOTS = [
  'C:\\Program Files\\Windows Kits\\10\\bin',
  'C:\\Program Files (x86)\\Windows Kits\\10\\bin',
];
const WINDOWS_KIT_TOOLS = ['makeappx.exe', 'makepri.exe', 'signtool.exe'];

async function hasWindowsKitTools(dir: string): Promise<boolean> {
  for (const tool of WINDOWS_KIT_TOOLS) {
    if (!(await pathExists(path.join(dir, tool)))) return false;
  }
  return true;
}

function compareVersionsDescending(a: string, b: string): number {
  const partsA = a.split('.').map(Number);
  const partsB = b.split('.').map(Number);
  for (let i = 0; i < Math.max(partsA.length, partsB.length); i++) {
    const diff = (partsB[i] ?? 0) - (partsA[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

/**
 * Locates a Windows SDK `bin` folder containing the MSIX tooling, preferring
 * the unversioned folder and then the newest installed SDK version. Returns
 * `undefined` when none is found so that `electron-windows-msix` can apply
 * its own default.
 */
async function findWindowsKit(): Promise<string | undefined> {
  // Older SDKs ship no arm64 makeappx.exe, so fall back to the x64 tools on
  // ARM hosts like electron-windows-msix does.
  const archs =
    process.env.PROCESSOR_ARCHITECTURE === 'ARM64' ? ['arm64', 'x64'] : ['x64'];
  for (const root of WINDOWS_KIT_ROOTS) {
    for (const arch of archs) {
      const unversioned = path.join(root, arch);
      if (await hasWindowsKitTools(unversioned)) return unversioned;
    }
    let versions: string[];
    try {
      versions = await fs.readdir(root);
    } catch {
      continue;
    }
    versions = versions
      .filter((version) => /^10\.\d+\.\d+\.\d+$/.test(version))
      .sort(compareVersionsDescending);
    for (const version of versions) {
      for (const arch of archs) {
        const candidate = path.join(root, version, arch);
        if (await hasWindowsKitTools(candidate)) return candidate;
      }
    }
  }
  return undefined;
}

// Ported from electron-windows-store/lib/sign.js: the subset of RFC 1779 /
// X.500 distinguished names that MakeCert accepted (no comma/space escaping).
const validDNRegex = (() => {
  const validKeyPattern = [
    'CN',
    'OU',
    'O',
    'STREET',
    'L',
    'ST',
    'C',
    'DC',
    'SN',
    'GN',
    'E',
    'S',
    'T',
    'G',
    'I',
    'SERIALNUMBER',
    '(?:OID\\.(0|[1-9][0-9]*)(?:\\.(0|[1-9][0-9]*))+)',
  ].join('|');
  // Every character is consumed by exactly one sub-pattern so the regex cannot
  // backtrack catastrophically: unquoted values exclude the RDN separators (and
  // `=`/`"`), and whitespace before a separator belongs to the unquoted value
  // or to the quoted alternative, never to the separator as well.
  const doubleQuotedValue = '"[^"]*"\\s*';
  const unquotedValue = '[^,;="]*';
  const keyValuePair = `(${validKeyPattern})=(${doubleQuotedValue}|${unquotedValue})`;
  return new RegExp(`^${keyValuePair}(?:[,;]\\s*${keyValuePair})*,?$`, 'i');
})();

/**
 * Builds a Microsoft Store package from a legacy `@electron-forge/maker-appx`
 * configuration using the MSIX tooling (`electron-windows-msix`).
 *
 * @deprecated Use `@electron-forge/maker-msix` instead. This maker is a
 * compatibility layer over the MSIX packaging code path: it maps
 * {@link MakerAppXConfig} onto `electron-windows-msix` options and writes a
 * `.msix` (not `.appx`) file to `make/appx/<arch>/`. Options without an MSIX
 * equivalent are ignored with a warning, and the maker no longer creates a
 * development certificate itself: when `devCert` is not set, signing is left
 * to `electron-windows-msix`, which generates a self-signed certificate that
 * is kept next to the `.msix` (`dev_cert.cer` / `dev_cert.pfx`).
 */
export default class MakerAppX extends MakerBase<MakerAppXConfig> {
  name = 'appx';

  defaultPlatforms: ForgePlatform[] = ['win32'];

  isSupportedOnCurrentPlatform(): boolean {
    return process.platform === 'win32';
  }

  async make({
    dir,
    makeDir,
    appName,
    packageJSON,
    targetArch,
  }: MakerOptions): Promise<string[]> {
    for (const option of UNSUPPORTED_OPTIONS) {
      if (this.config[option] !== undefined) {
        this.warn(
          `The "${option}" option is not supported by @electron-forge/maker-appx anymore and will be ignored. ` +
            'Migrate to @electron-forge/maker-msix.',
        );
      }
    }

    // Signing options are only forwarded together with a devCert; without
    // one, electron-windows-msix signs with its own development certificate.
    if (!this.config.devCert) {
      for (const option of ['certPass', 'signtoolParams'] as const) {
        if (this.config[option] !== undefined) {
          this.warn(
            `The "${option}" option is ignored by @electron-forge/maker-appx because "devCert" is not set. ` +
              'Set "devCert" to sign with your own certificate.',
          );
        }
      }
    }

    if (this.config.assets && !this.config.manifest) {
      const missing: string[] = [];
      for (const asset of REQUIRED_ASSETS) {
        if (!(await pathExists(path.join(this.config.assets, asset)))) {
          missing.push(asset);
        }
      }
      if (missing.length > 0) {
        throw new Error(
          `The "assets" folder '${this.config.assets}' is missing ${missing.join(', ')}, which the generated AppxManifest.xml refers to. ` +
            'electron-windows-msix uses different asset file names than electron-windows-store ' +
            '(e.g. SampleAppx.44x44.png is now Square44x44Logo.png, SampleAppx.150x150.png is now Square150x150Logo.png ' +
            'and SampleAppx.50x50.png is now icon.png). Rename the files or provide a custom "manifest" that references them.',
        );
      }
    }

    const authorName = getNameFromAuthor(packageJSON.author);
    const publisher =
      this.config.publisher ?? (authorName && `CN=${authorName}`);
    if (!publisher) {
      throw new Error(
        'Please set the "publisher" option in the maker config or "author.name" in package.json for the appx target',
      );
    }
    // Like electron-windows-store, only validate the publisher when Forge has
    // no user-supplied certificate; with a devCert it is forwarded verbatim.
    if (!this.config.devCert && !validDNRegex.test(publisher)) {
      throw new Error(
        `Received invalid publisher name: '${publisher}' did not conform to X.500 distinguished name syntax.`,
      );
    }

    let packageVersion =
      this.config.packageVersion ?? `${packageJSON.version}.0`;
    if (/[-+]/.test(packageVersion)) {
      if (this.config.makeVersionWinStoreCompatible) {
        packageVersion = this.normalizeWindowsVersion(packageVersion);
      } else {
        throw new Error(
          "Windows Store version numbers don't support semver beta tags. To " +
            'automatically fix this, set makeVersionWinStoreCompatible to true or ' +
            'explicitly set packageVersion to a version of the format X.Y.Z.A',
        );
      }
    }

    const packageName =
      this.config.packageName ?? packageJSON.name.replace(/-/g, '');

    // Clear the previous artifact so a re-run does not fail in `move()`.
    const outPath = path.resolve(makeDir, 'appx', targetArch);
    await this.ensureDirectory(outPath);

    // Do all the scratch work in a temporary folder (outside of outPath)
    const tmpFolder = await fs.mkdtemp(
      path.resolve(os.tmpdir(), 'appx-maker-'),
    );

    try {
      const result = await packageMSIX({
        appDir: dir,
        outputDir: tmpFolder,
        packageName: `${packageName}.msix`,
        appManifest: this.config.manifest,
        packageAssets: this.config.assets,
        windowsKitPath: this.config.windowsKit ?? (await findWindowsKit()),
        createPri: this.config.makePri ?? false,
        windowsSignOptions: this.config.devCert
          ? {
              certificateFile: this.config.devCert,
              certificatePassword: this.config.certPass,
              signWithParams: this.config.signtoolParams,
            }
          : undefined,
        manifestVariables: {
          packageIdentity: packageName,
          publisher,
          packageVersion,
          packageDisplayName: this.config.packageDisplayName ?? appName,
          packageDescription:
            this.config.packageDescription ??
            (packageJSON.description || appName),
          packageBackgroundColor: this.config.packageBackgroundColor,
          // electron-windows-store took the executable relative to the package
          // root (`app\\Name.exe`); electron-windows-msix prepends `app\\` itself.
          appExecutable:
            this.config.packageExecutable?.replace(/^app[\\/]/i, '') ??
            `${appName}.exe`,
          targetArch: toMsixArch(targetArch),
        },
      });

      const outputPath = path.resolve(outPath, `${packageName}.msix`);
      await move(result.msixPackage, outputPath);

      // Without a devCert, electron-windows-msix signs with a self-signed
      // certificate it writes next to the package in `outputDir`. Keep it
      // beside the .msix (like the old maker did) so it can be trusted on a
      // test device; the temp folder is deleted below. The .msix is already in
      // place, so a failure here (e.g. EBUSY on Windows) must not fail make().
      if (!this.config.devCert) {
        try {
          for (const certFile of ['dev_cert.cer', 'dev_cert.pfx']) {
            const certPath = path.resolve(tmpFolder, certFile);
            if (await pathExists(certPath)) {
              await move(certPath, path.resolve(outPath, certFile));
            }
          }
        } catch (err) {
          this.warn(
            `Could not keep the development certificate next to the package: ${err instanceof Error ? err.message : String(err)}`,
          );
        }
      }

      return [outputPath];
    } finally {
      // A failed cleanup (e.g. a lingering handle on Windows) must not turn a
      // successful make() into an error: the .msix has already been moved.
      try {
        await fs.rm(tmpFolder, { recursive: true, force: true });
      } catch (err) {
        this.warn(
          `Could not remove the temporary folder "${tmpFolder}": ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }
  }

  private warn(message: string): void {
    console.warn(
      styleText('yellow', '⚠'),
      styleText('yellow', `WARNING: ${message}`),
    );
  }
}

export { MakerAppX, MakerAppXConfig };
