name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  NODE_VERSION: 20.17.0

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write # Required for OIDC trusted publishing
    steps:
      - name: Configure git
        run: git config --global core.autocrlf input

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Fetch full history for lerna version detection
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      # TODO(Forge 8): remove this once we can upgrade to `@electron/rebuild` v4
      - name: Set up Python 3.11 (with distutils)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:fast

      - name: Configure Git for publishing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish to npm
        run: npx lerna publish from-package --yes
